apiVersion: v2
name: opengatellm-stack
description: A Helm chart for OpenGateLLM Stack
type: application
version: 0.8.3
appVersion: "0.3.6"

dependencies:
  - name: opengatellm-core
    version: "0.3.2"
    repository: "file://../opengatellm-core"
    condition: opengatellm-core.enabled
  - name: vllm-stack
    version: "0.1.8"
    repository: "https://vllm-project.github.io/production-stack"
    condition: vllm-stack.enabled
    tags:
      - opengatellm-stack-inference
