apiVersion: v2
name: opengatellm-stack
description: A Helm chart for OpenGateLLM Stack
type: application
version: 0.6.0
appVersion: "0.3.6"

dependencies:
  - name: opengatellm
    version: "0.1.0"
    repository: "file://../opengatellm"
    condition: opengatellm.enabled
  - name: vllm-stack
    version: "0.1.8"
    repository: "https://vllm-project.github.io/production-stack"
    condition: vllm-stack.enabled
    tags:
      - opengatellm-stack-inference
