apiVersion: v2
name: opengatellm-stack
description: A Helm chart for OpenGateLLM Stack
type: application
version: 0.4.0
appVersion: "0.3.5post2"

dependencies:
  - name: opengatellm
    version: "0.1.0"
    repository: "file://../opengatellm"
    condition: opengatellm.enabled
  - name: vllm-stack
    version: "0.1.8"
    repository: "https://vllm-project.github.io/production-stack"
    condition: vllm-stack.enabled
    tags:
      - opengatellm-stack-inference
  - name: eck-operator-crds
    version: "3.2.0"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
    tags:
      - opengatellm-stack-search
  - name: eck-operator
    version: "3.2.0"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
    tags:
      - opengatellm-stack-search
