{{- if .Values.embeddings.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opengatellm-stack-embeddings
  labels:
    app: opengatellm-stack-embeddings
    {{- include "opengatellm-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: embeddings
spec:
  replicas: {{ .Values.embeddings.replicas }}
  selector:
    matchLabels:
      app: opengatellm-stack-embeddings
  template:
    metadata:
      labels:
        app: opengatellm-stack-embeddings
    spec:
      {{- with .Values.embeddings.nodeSelector }}
      nodeSelector:
        {{ . | toYaml }}
      {{- end }}
      {{- if .Values.embeddings.securityContext }}
      securityContext:
        {{- toYaml .Values.embeddings.securityContext | nindent 12 }}
      {{- end }}
      containers:
      - name: bge-embeddings
        image: {{ .Values.embeddings.image.repository }}:{{ .Values.embeddings.image.tag }}
        imagePullPolicy: {{ .Values.embeddings.image.pullPolicy }}
        command: [ "text-embeddings-router" ]
        args: [ "--model-id", "{{ .Values.embeddings.config.model }}" ]
        env:
          - name: PORT
            value: {{ .Values.embeddings.config.port | quote }}
        resources:
          limits:
            cpu: {{ .Values.embeddings.resources.limits.cpu | quote }}
            memory: {{ .Values.embeddings.resources.limits.memory }}
            nvidia.com/gpu: {{ .Values.embeddings.resources.limits.gpu }}
          requests:
            cpu: {{ .Values.embeddings.resources.requests.cpu | quote }}
            memory: {{ .Values.embeddings.resources.requests.memory }}
            nvidia.com/gpu: {{ .Values.embeddings.resources.requests.gpu }}
        {{- if .Values.embeddings.probes.liveness.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.embeddings.probes.liveness.path }}
            port: {{ .Values.embeddings.config.port }}
          initialDelaySeconds: {{ .Values.embeddings.probes.liveness.initialDelaySeconds }}
          timeoutSeconds: 30
          periodSeconds: {{ .Values.embeddings.probes.liveness.periodSeconds }}
        {{- end }}
        {{- if .Values.embeddings.probes.readiness.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.embeddings.probes.readiness.path }}
            port: {{ .Values.embeddings.config.port }}
          initialDelaySeconds: {{ .Values.embeddings.probes.readiness.initialDelaySeconds }}
          timeoutSeconds: 30
          periodSeconds: {{ .Values.embeddings.probes.readiness.periodSeconds }}
        {{- end }}
        {{- if .Values.embeddings.containerSecurityContext }}
        securityContext:
          {{- toYaml .Values.embeddings.containerSecurityContext | nindent 12 }}
        {{- end }}
{{- end }}
