apiVersion: v1
kind: Secret
metadata:
  name: huggingface-token
  labels:
    {{- include "opengatellm-stack.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.huggingface.token | b64enc | quote }}
