{{- if and .Values.opengatellm.enabled .Values.playground.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.playground.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "opengatellm-stack.labels" . | nindent 4 }}
    {{- range $labelKey, $labelValue := .Values.playground.ingress.labels }}
    {{ $labelKey }}: {{ $labelValue | toYaml }}
    {{- end }}
  name: opengatellm-stack-playground
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.playground.ingress.ingressClassName }}
  {{- if .Values.playground.ingress.tls }}
  tls:
    {{- range .Values.playground.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
      {{- with .secretName }}
      secretName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.playground.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: opengatellm-stack-playground
                port:
                  number: {{ $.Values.playground.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
