{{- if .Values.opengatellm.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opengatellm-stack-playground
  labels:
    {{- include "opengatellm-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: playground
spec:
  replicas: {{ .Values.playground.replicas }}
  selector:
    matchLabels:
      app: opengatellm-stack-playground
  template:
    metadata:
      labels:
        app: opengatellm-stack-playground
    spec:
      {{- with .Values.playground.nodeSelector }}
      nodeSelector:
        {{ . | toYaml }}
      {{- end }}
      {{- if .Values.playground.securityContext }}
      securityContext:
        {{- toYaml .Values.playground.securityContext | nindent 12 }}
      {{- end }}
      containers:
      - name: playground
        image: {{ .Values.playground.image.repository }}:{{ .Values.playground.image.tag }}
        imagePullPolicy: {{ .Values.playground.image.pullPolicy }}
        env:
          - name: CONFIG_FILE
            value: "/home/opengatellm/conf/config.yml"
          - name: OPENGATELLM_URL
            value: {{ .Values.opengatellm.opengatellm.structuredConfig.playground.api_url | quote }}
          {{- if not .Values.opengatellm.redis.existingRedisSecret }}
          - name: REDIS_HOST
            value: {{ printf "%s-redis" .Release.Name }}
          - name: REDIS_PORT
            value: "{{ default 6379 .Values.opengatellm.redis.redis.port }}"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-redis" .Release.Name }}
                key: {{ default .Values.opengatellm.redis.authKey .Values.opengatellm.redis.sentinel.authKey }}
          {{- end }}
          {{- if not .Values.opengatellm.postgresql.existingPostgresSecret }}
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-app" .Values.opengatellm.postgresql.clusterName }}
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-app" .Values.opengatellm.postgresql.clusterName }}
                key: port
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-app" .Values.opengatellm.postgresql.clusterName }}
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-app" .Values.opengatellm.postgresql.clusterName }}
                key: password
          {{- end }}
        envFrom:
          {{- if .Values.opengatellm.redis.existingRedisSecret }}
          - secretRef:
              name: {{ .Values.opengatellm.redis.existingRedisSecret }}
          {{- end }}
          {{- if .Values.opengatellm.postgresql.existingPostgresSecret }}
          - secretRef:
              name: {{ .Values.opengatellm.postgresql.existingPostgresSecret }}
          {{- end }}
        ports:
          - containerPort: {{ .Values.playground.service.targetPort }}
        volumeMounts:
          - name: playground-config-vol
            mountPath: /home/opengatellm/conf
            readOnly: true
        {{- if .Values.playground.probes.readiness }}
        readinessProbe:
          httpGet:
            path: {{ .Values.playground.probes.readiness.path }}
            port: {{ .Values.playground.service.targetPort }}
          initialDelaySeconds: {{ .Values.playground.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.playground.probes.readiness.periodSeconds }}
        {{- end }}
        {{- if .Values.playground.probes.liveness }}
        livenessProbe:
          httpGet:
            path: {{ .Values.playground.probes.liveness.path }}
            port: {{ .Values.playground.service.targetPort }}
          initialDelaySeconds: {{ .Values.playground.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.playground.probes.liveness.periodSeconds }}
        {{- end }}
        {{- if .Values.playground.containerSecurityContext }}
        securityContext:
          {{- toYaml .Values.playground.containerSecurityContext | nindent 12 }}
        {{- end }}
        {{- if .Values.playground.resources }}
        resources:
          {{- toYaml .Values.playground.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: playground-config-vol
          configMap:
            name: opengatellm-stack-playground-config
{{- end }}
