apiVersion: v1
kind: Service
metadata:
  name: opengatellm
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "opengatellm.labels" . | nindent 4 }}
spec:
  selector:
    app: opengatellm
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.opengatellm.service.port }}
      protocol: TCP
      targetPort: http
      name: http
  type: {{ .Values.opengatellm.service.type }}