apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm.fullname" . }}-api-key
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
type: Opaque
data:
  api_key: {{ .Values.api_key | b64enc | quote }}
