vllm:
  api_key: "changeme"

huggingface:
  token: "changeme"

whisperx:
  api_key: "changeme"

elasticsearch:
  security:
    elasticPassword: "changeme"

opengatellm:
  config:
    dependencies:
      elasticsearch:
        basic_auth:
          - "elastic"
          - "changeme"