{{- if .Values.opengatellm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: opengatellm-stack-api-config
  labels:
    {{- include "opengatellm-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  config.yml: |
    # opengatellm config.yml
    {{- toYaml .Values.opengatellm.config | nindent 4 }}
{{- end }}
