apiVersion: v1
kind: Service
metadata:
  name: opengatellm-core
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "opengatellm-core.labels" . | nindent 4 }}
spec:
  selector:
    app: opengatellm-core
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.api.service.port }}
      protocol: TCP
      targetPort: http
      name: http
  type: {{ .Values.api.service.type }}