apiVersion: apps/v1
kind: Deployment
metadata:
  name: opengatellm-core
  namespace: {{ default .Release.Namespace .Values.namespaceOverride | quote }}
  {{- with .Values.opengatellmCore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "opengatellm-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.opengatellmCore.replicas }}
  {{- with .Values.opengatellmCore.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      app: opengatellm-core
  {{- with .Values.opengatellmCore.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- include "opengatellm-core.config.checksum" . | nindent 8 }}
      labels:
        app: opengatellm-core
        app.kubernetes.io/component: api
      namespace: {{ default .Release.Namespace .Values.namespaceOverride | quote }}
    spec:
      serviceAccountName: {{ template "opengatellm-core.serviceAccountName" . }}
      {{- if .Values.opengatellmCore.priorityClassName }}
      priorityClassName: {{ .Values.opengatellmCore.priorityClassName }}
      {{- end }}
      {{- with .Values.opengatellmCore.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opengatellmCore.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: opengatellm-core
          image: "{{ .Values.opengatellmCore.image.repository }}:{{ .Values.opengatellmCore.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.opengatellmCore.image.pullPolicy }}
          {{- if .Values.opengatellmCore.extraArgs }}
          args:
          {{- range $key, $value := .Values.opengatellmCore.extraArgs }}
            - -{{ $key }}={{ $value }}
          {{- end }}
          {{- end }}
          volumeMounts:
            {{- if .Values.opengatellmCore.extraVolumeMounts }}
              {{ toYaml .Values.opengatellmCore.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: config
              mountPath: /home/opengatellm/conf
              readOnly: true
            - name: logging-config
              mountPath: /home/opengatellm/logging
              readOnly: true
          env:
          - name: CONFIG_FILE
            value: "/home/opengatellm/conf/config.yml"
          {{- with .Values.opengatellmCore.gunicornArgs }}
          - name: GUNICORN_CMD_ARGS
            value: {{ . | quote }}
          {{- end }}
          {{- if not .Values.redis.existingRedisSecret }}
          - name: REDIS_HOST
            value: {{ printf "%s-redis" .Release.Name }}
          - name: REDIS_PORT
            value: "{{ default 6379 .Values.redis.redis.port }}"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-redis" .Release.Name }}
                key: {{ default .Values.redis.authKey .Values.redis.sentinel.authKey }}
          {{- end }}
          {{- if not .Values.postgresql.existingPostgresSecret }}
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-app" .Values.postgresql.clusterName }}
                key: uri
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-app" .Values.postgresql.clusterName }}
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-app" .Values.postgresql.clusterName }}
                key: port
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-app" .Values.postgresql.clusterName }}
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-app" .Values.postgresql.clusterName }}
                key: password
          {{- end }}
          envFrom:
            {{- if .Values.opengatellmCore.existingModelSecret }}
            - secretRef:
                name: {{ .Values.opengatellmCore.existingModelSecret }}
            {{- end }}
            {{- if .Values.postgresql.existingPostgresSecret }}
            - secretRef:
                name: {{ .Values.postgresql.existingPostgresSecret }}
            {{- end }}
            {{- if .Values.redis.existingRedisSecret }}
            - secretRef:
                name: {{ .Values.redis.existingRedisSecret }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.opengatellmCore.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.opengatellmCore.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.opengatellmCore.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.opengatellmCore.containerSecurityContext | nindent 12 }}
{{- if .Values.opengatellmCore.extraContainers }}
{{ toYaml .Values.opengatellmCore.extraContainers | indent 8}}
{{- end }}
      {{- with .Values.opengatellmCore.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opengatellmCore.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opengatellmCore.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.opengatellmCore.terminationGracePeriodSeconds }}
      {{- with .Values.opengatellmCore.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: opengatellm-core-config
        - name: logging-config
          configMap:
            name: opengatellm-core-logging-config
        {{- if .Values.opengatellmCore.extraVolumes }}
        {{- toYaml .Values.opengatellmCore.extraVolumes | nindent 8}}
        {{- end }}

