apiVersion: v1
kind: ConfigMap
metadata:
  name: opengatellm-core-config
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "opengatellm-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  config.yml: |
    {{- include "opengatellm-core.calculatedConfig" . | nindent 4 }}
